Repository ourtreering/ourtreering.github.io, pull requests merged in 2021-06, with the labels that each got.

#2 개발팀 소개 카테고리에 carousel 추가
  _includes/about-banner.html
  _includes/head.html
  _includes/nav.html
  _sass/_nav.scss
  meta/treering_banner1.png
  meta/treering_banner2.png
  meta/treering_banner3.png
  meta/treering_logo.png
Labels: feature

#4 fix:배너 이미지 잘림 수정
  _includes/about-banner.html
  meta/treering_banner1.jpg
  meta/treering_banner1.png
  meta/treering_banner2.jpg
  meta/treering_banner2.png
  meta/treering_banner3.jpg
  meta/treering_banner3.png
Labels: fix

#6 fix:카테고리 hash-tag별 포스트 보기
  _includes/post-list.html
  _sass/_catalogue.scss
  tech/2106250002/index.md
Labels: fix

#8 Add:헤더사진 추가
  tech/2106281151/img/2106281.jpg
  tech/2106281151/index.md
Labels: documentation

#9 Add:헤더사진 이름변경
  tech/2106281151/img/21062812.jpg
  tech/2106281151/index.md
Labels: documentation

#10 ADD: 규진 자기소개 추가
  Gemfile.lock
  _data/members.yml
  about/img/971121.jpg
Labels: documentation
